// components/showsdata.js

let data = [
  {
    date1: "Jan. 27-28 at 7:30 pm / 9:00 pm",
    date2: "",
    venue: "Smalls NYC",
    address1: "183 West 10th Street, basement",
    address2: "New York City, NY",
    phone: "",
    group: "Dave Stryker Trio",
    musician1: "Dave Stryker - guitar",
    musician2: "Jared Gold - organ",
    musician3: "McClenty Hunter - drums",
    musician4: "",
    musician5: "",
  },
  {
    date1: "Feb. 4 at 7:00 pm / 9:00 pm",
    date2: "",
    venue: "Shanghai Jazz",
    address1: "24 Main Street",
    address2: "Madison, NJ",
    phone: "973-822-2899",
    group: "Dave Stryker Trio",
    musician1: "Dave Stryker - guitar",
    musician2: "Pat Bianchi - organ",
    musician3: "McClenty Hunter - drums",
    musician4: "",
    musician5: "",
  },
  {
    date1: "March 4 at 7:00 pm / 9:00 pm",
    date2: "",
    venue: "Scullers",
    address1: "Double Tree Hotel",
    address2: "Cambridge, MA",
    phone: "617-562-4148",
    group: "Dave Stryker Trio with Walter Smith III",
    musician1: "Dave Stryker - guitar",
    musician2: "Jared Gold - organ",
    musician3: "McClenty Hunter - drums",
    musician4: "Walter Smith III - tenor sax",
    musician5: "",
  },
  {
    date1: "March 17 at 7:00 pm / 9:00 pm",
    date2: "",
    venue: "Shanghai Jazz",
    address1: "24 Main Street",
    address2: "Madison, NJ",
    phone: "973-822-2899",
    group: "Dave Stryker Trio",
    musician1: "Dave Stryker - guitar",
    musician2: "Jared Gold - organ",
    musician3: "McClenty Hunter - drums",
    musician4: "",
    musician5: "",
  },
  {
    date1: "April 7-8 at 7:00 pm / 9:15 pm",
    date2: "April 9 at 5:00 pm / 7:30 pm",
    venue: "Keystone Korner",
    address1: "1350 Lancaster Street",
    address2: "Baltimore, MD",
    phone: "410-946-6726",
    group: "Dave Stryker Trio with Warren Wolf",
    musician1: "Dave Stryker - guitar",
    musician2: "Jared Gold - organ",
    musician3: "McClenty Hunter - drums",
    musician4: "Warren Wolf - vibes",
    musician5: "",
  },
  {
    date1: "April 14 at 7:00 pm / 9:00 pm",
    date2: "",
    venue: "Shanghai Jazz",
    address1: "24 Main Street",
    address2: "Madison, NJ",
    phone: "973-822-2899",
    group: "Dave Stryker Trio",
    musician1: "Dave Stryker - guitar",
    musician2: "Jared Gold - organ",
    musician3: "McClenty Hunter - drums",
    musician4: "",
    musician5: "",
  },
  {
    date1: "April 21 at 7:00 pm / 9:30 pm",
    date2: "",
    venue: "The Jazz Kitchen",
    address1: "5377 N College Avenue",
    address2: "Indianapolis, IN",
    phone: "317-253-4900",
    group: "Dave Stryker Organ Trio with Bob Mintzer",
    musician1: "Dave Stryker Quartet",
    musician2: "Dave Stryker - guitar",
    musician3: "Rob Dixon - tenor sax",
    musician4: "Kendall Carter - organ",
    musician5: "Sean Dobbins - drums",
  },
  {
    date1: "July 4-6 at 7:00 pm / 9:30 pm",
    date2: "July 7-8 at 8:30 pm / 10:30 pm",
    venue: "Birdland NYC",
    address1: "315 W 44th St #5402",
    address2: "New York, NY",
    phone: "212-581-3080",
    group: "Dave Stryker Organ Trio with Bob Mintzer",
    musician1: "Dave Stryker - guitar",
    musician2: "Bob Mintzer - tenor sax",
    musician3: "Jared Gold - organ",
    musician4: "McClenty Hunter - drums",
    musician5: "",
  },
];
